item {
  id: 1
  name: '1A'
}

item {
  id: 2
  name: '2A'
}

item {
  id: 3
  name: '3A'
}

item {
  id: 4
  name: '4A'
}

item {
  id: 5
  name: '5A'
}

item {
  id: 6
  name: '6A'
}

item {
  id: 7
  name: '7A'
}

item {
  id: 8
  name: '8A'
}

item {
  id: 9
  name: '9A'
}

item {
  id: 10
  name: '2N'
}

item {
  id: 11
  name: '3N'
}

item {
  id: 12
  name: '4N'
}

item {
  id: 13
  name: '5N'
}

item {
  id: 14
  name: '6N'
}

item {
  id: 15
  name: '7N'
}

item {
  id: 16
  name: '8N'
}

item {
  id: 17
  name: '9N'
}

item {
  id: 18
  name: '1N'
}

item {
  id: 19
  name: 'X'
}

item {
  id: 20
  name: 'XA'
}

item {
  id: 21
  name: 'box'
}
